/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DropsRouteImport } from './routes/drops'
import { Route as IndependentRouteImport } from './routes/independent'
import { Route as SaturdayRouteImport } from './routes/saturday'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as CollectionSlugRouteImport } from './routes/collection.$slug'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as SaturdayIndexRouteImport } from './routes/saturday.index'
import { Route as SaturdayBoardRouteImport } from './routes/saturday.board'
import { Route as SaturdaySixRouteImport } from './routes/saturday.six'
import { Route as SaturdayWireRouteImport } from './routes/saturday.wire'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DropsRoute = DropsRouteImport.update({
  id: '/drops',
  path: '/drops',
  getParentRoute: () => rootRouteImport,
} as any)
const IndependentRoute = IndependentRouteImport.update({
  id: '/independent',
  path: '/independent',
  getParentRoute: () => rootRouteImport,
} as any)
const SaturdayRoute = SaturdayRouteImport.update({
  id: '/saturday',
  path: '/saturday',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionSlugRoute = CollectionSlugRouteImport.update({
  id: '/collection/$slug',
  path: '/collection/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SaturdayIndexRoute = SaturdayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SaturdayRoute,
} as any)
const SaturdayBoardRoute = SaturdayBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => SaturdayRoute,
} as any)
const SaturdaySixRoute = SaturdaySixRouteImport.update({
  id: '/six',
  path: '/six',
  getParentRoute: () => SaturdayRoute,
} as any)
const SaturdayWireRoute = SaturdayWireRouteImport.update({
  id: '/wire',
  path: '/wire',
  getParentRoute: () => SaturdayRoute,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/drops': typeof DropsRoute
  '/independent': typeof IndependentRoute
  '/saturday': typeof SaturdayRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/collection/$slug': typeof CollectionSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/saturday/board': typeof SaturdayBoardRoute
  '/saturday/six': typeof SaturdaySixRoute
  '/saturday/wire': typeof SaturdayWireRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/saturday/': typeof SaturdayIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/drops': typeof DropsRoute
  '/independent': typeof IndependentRoute
  '/collection/$slug': typeof CollectionSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/saturday/board': typeof SaturdayBoardRoute
  '/saturday/six': typeof SaturdaySixRoute
  '/saturday/wire': typeof SaturdayWireRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/saturday': typeof SaturdayIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/drops': typeof DropsRoute
  '/independent': typeof IndependentRoute
  '/saturday': typeof SaturdayRouteWithChildren
  '/shop': typeof ShopRouteWithChildren
  '/collection/$slug': typeof CollectionSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/saturday/board': typeof SaturdayBoardRoute
  '/saturday/six': typeof SaturdaySixRoute
  '/saturday/wire': typeof SaturdayWireRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/saturday/': typeof SaturdayIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/drops'
    | '/independent'
    | '/saturday'
    | '/shop'
    | '/collection/$slug'
    | '/order/$id'
    | '/saturday/board'
    | '/saturday/six'
    | '/saturday/wire'
    | '/shop/$slug'
    | '/saturday/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/drops'
    | '/independent'
    | '/collection/$slug'
    | '/order/$id'
    | '/saturday/board'
    | '/saturday/six'
    | '/saturday/wire'
    | '/shop/$slug'
    | '/saturday'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/drops'
    | '/independent'
    | '/saturday'
    | '/shop'
    | '/collection/$slug'
    | '/order/$id'
    | '/saturday/board'
    | '/saturday/six'
    | '/saturday/wire'
    | '/shop/$slug'
    | '/saturday/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  DropsRoute: typeof DropsRoute
  IndependentRoute: typeof IndependentRoute
  SaturdayRoute: typeof SaturdayRouteWithChildren
  ShopRoute: typeof ShopRouteWithChildren
  CollectionSlugRoute: typeof CollectionSlugRoute
  OrderIdRoute: typeof OrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drops': {
      id: '/drops'
      path: '/drops'
      fullPath: '/drops'
      preLoaderRoute: typeof DropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/independent': {
      id: '/independent'
      path: '/independent'
      fullPath: '/independent'
      preLoaderRoute: typeof IndependentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saturday': {
      id: '/saturday'
      path: '/saturday'
      fullPath: '/saturday'
      preLoaderRoute: typeof SaturdayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection/$slug': {
      id: '/collection/$slug'
      path: '/collection/$slug'
      fullPath: '/collection/$slug'
      preLoaderRoute: typeof CollectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saturday/': {
      id: '/saturday/'
      path: '/'
      fullPath: '/saturday/'
      preLoaderRoute: typeof SaturdayIndexRouteImport
      parentRoute: typeof SaturdayRoute
    }
    '/saturday/board': {
      id: '/saturday/board'
      path: '/board'
      fullPath: '/saturday/board'
      preLoaderRoute: typeof SaturdayBoardRouteImport
      parentRoute: typeof SaturdayRoute
    }
    '/saturday/six': {
      id: '/saturday/six'
      path: '/six'
      fullPath: '/saturday/six'
      preLoaderRoute: typeof SaturdaySixRouteImport
      parentRoute: typeof SaturdayRoute
    }
    '/saturday/wire': {
      id: '/saturday/wire'
      path: '/wire'
      fullPath: '/saturday/wire'
      preLoaderRoute: typeof SaturdayWireRouteImport
      parentRoute: typeof SaturdayRoute
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface SaturdayRouteChildren {
  SaturdayBoardRoute: typeof SaturdayBoardRoute
  SaturdaySixRoute: typeof SaturdaySixRoute
  SaturdayWireRoute: typeof SaturdayWireRoute
  SaturdayIndexRoute: typeof SaturdayIndexRoute
}

const SaturdayRouteChildren: SaturdayRouteChildren = {
  SaturdayBoardRoute: SaturdayBoardRoute,
  SaturdaySixRoute: SaturdaySixRoute,
  SaturdayWireRoute: SaturdayWireRoute,
  SaturdayIndexRoute: SaturdayIndexRoute,
}

const SaturdayRouteWithChildren = SaturdayRoute._addFileChildren(
  SaturdayRouteChildren,
)

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  DropsRoute: DropsRoute,
  IndependentRoute: IndependentRoute,
  SaturdayRoute: SaturdayRouteWithChildren,
  ShopRoute: ShopRouteWithChildren,
  CollectionSlugRoute: CollectionSlugRoute,
  OrderIdRoute: OrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
